### ISSUE TITLE
URL's aren't formatted correctly

### ISSUE THREAD

**Issue by jonfriesen** [MegaMakers/amplifyBot#15]
Need to handle URLs currently something like `megamaker.co` appears as `megamaker.co|megamaker.co`

eg
![image](https://user-images.githubusercontent.com/2105302/68258091-71e87280-ffea-11e9-8c1b-118a998eb5c7.png)

**Comment by vineet-sinha** [comment]
So what is really happening is `megamaker.co` shows up as `<http://megamaker.co|megamaker.co>`

But, I am clearing out the `<>`

What needs to be done is to clear out everything till the `|`

(Working on this)
