### ISSUE TITLE
Change approvals to thumbs up / thumbs down

### ISSUE THREAD

**Issue by jonfriesen** [MegaMakers/amplifyBot#17]
Currently when approving a message, if a user adds any three reactions we approve the tweet. Instead lets check for a total different of plus 3 thumbs up.

So if a user has 3 thumbs up but 1 thumbs down they require one more thumbs down before the post will happen. If the user has 4 thumbs down and 1 thumbs up the tweet will be cancelled.

I expect this to be used for community moderation, for example I craft a tweet with a spelling mistake, but I've been working on it so long I miss that mistake, the rest of the chat with fresh eyes will see it and be able to stop it so I can fix the tweet.

**Comment by vineet-sinha** [comment]
@jonfriesen - is there a typo in the above report? Should it instead be:

> So if a user has 3 thumbs up but 1 thumbs down they require one more thumbs `up` before the post will happen. If the user has 4 thumbs down and 1 thumbs up the tweet will be cancelled.

**Comment by jonfriesen** [comment]
@vineet-sinha It's a kind of first past the post moderation system. Whether the user gets a net difference of 3 thumbs up or thumbs down that is the action that is taken.

For example, if my post gets a 2 thumbs up, then a thumbs down, then two more thumbs up, my post will have 4 thumbs up and 1 thumbs down making the difference +3 thumbs up.
