### ISSUE TITLE
Add total daily limit

### ISSUE THREAD

**Issue by jonfriesen** [MegaMakers/amplifyBot#2]
Implement a max posts per day. Consider designing a queue system (maybe using the KV from #1 ).

**Comment by vineet-sinha** [comment]
@jonfriesen - isn't this implemented in https://github.com/MegaMakers/amplifyBot/blob/master/index.js#L23, i.e. by `checkUserPostLimits `?

Yes, right now it configured for 1 minute, but we can change easily to 24 hours.
