### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jonfriesen** [MegaMakers/amplifyBot#7]
Need to improve the three main areas:

- User Usage
- Configuration
- Running
  - Dev environments would also be helpful

**Comment by vineet-sinha** [comment]
@jonfriesen - I did a round of improving documentation. 

With regards to Dev environment - we could use a workspace I created sometime back (and primarily use for such testing).

Let me know if there is anything else here.

**Comment by jonfriesen** [comment]
That's not a bad idea. We can share API keys etc on there with trust worthy individuals :P Can you send me an invite?

**Comment by mabadir** [comment]
Hi guys!
Can I get into the Workspace?

**Comment by vineet-sinha** [comment]
@jonfriesen - what is the process? Does Mina need to submit a PR or do we just add him to repo?

**Comment by jonfriesen** [comment]
@mabadir has been added. Thanks!
